apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: code-quarkus-appaa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: code-quarkus-appaa
    app.kubernetes.io/part-of: test-app-165520954
  name: code-quarkus-appaa
  namespace: kkanova
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: code-quarkus-appaa
status:
  loadBalancer: {}
